[comment]: # Removed global builder to allow per-service dockerfile paths
[service.action-server]
root = "action-server"
dockerfile = "action-server/Dockerfile"
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health-check"
healthcheckTimeout = 300

[service.action-server.build]
context = "action-server"
dockerfile = "Dockerfile"

[service.action-server.env]
PORT = "8000"
PYTHONPATH = "/app"
ENVIRONMENT = "production"
GEMINI_API_KEY = "${GEMINI_API_KEY}"
TWILIO_ACCOUNT_SID = "${TWILIO_ACCOUNT_SID}"
TWILIO_AUTH_TOKEN = "${TWILIO_AUTH_TOKEN}"
TWILIO_WHATSAPP_NUMBER = "${TWILIO_WHATSAPP_NUMBER}"
TWILIO_SMS_NUMBER = "${TWILIO_SMS_NUMBER}"
HEALTH_API_KEY = "${HEALTH_API_KEY}"
HEALTH_API_URL = "${HEALTH_API_URL}"

[service.rasa-server]
root = "rasa"
dockerfile = "rasa/Dockerfile"
startCommand = "rasa run --enable-api --cors '*' --port $PORT --host 0.0.0.0"
healthcheckPath = "/status"
healthcheckTimeout = 300

[service.rasa-server.build]
context = "rasa"
dockerfile = "Dockerfile"

[service.rasa-server.env]
PORT = "5005"
RASA_MODEL_SERVER = "http://localhost:5005"

[service.web-dashboard]
root = "web-dashboard"
dockerfile = "web-dashboard/Dockerfile"
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/"

[service.web-dashboard.build]
context = "web-dashboard"
dockerfile = "Dockerfile"

[service.web-dashboard.env]
PORT = "80"
