[build]
builder = "NIXPACKS"

[[services]]
id = "action-server"
name = "action-server"
source = "action-server"
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health-check"
healthcheckTimeout = 300

[services.action-server.env]
PORT = "8000"
PYTHONPATH = "/app"
ENVIRONMENT = "production"
GEMINI_API_KEY = "${GEMINI_API_KEY}"
TWILIO_ACCOUNT_SID = "${TWILIO_ACCOUNT_SID}"
TWILIO_AUTH_TOKEN = "${TWILIO_AUTH_TOKEN}"
TWILIO_WHATSAPP_NUMBER = "${TWILIO_WHATSAPP_NUMBER}"
TWILIO_SMS_NUMBER = "${TWILIO_SMS_NUMBER}"
HEALTH_API_KEY = "${HEALTH_API_KEY}"
HEALTH_API_URL = "${HEALTH_API_URL}"

[[services]]
id = "rasa-server"
name = "rasa-server"
source = "rasa"
startCommand = "rasa run --enable-api --cors '*' --port $PORT --host 0.0.0.0"
healthcheckPath = "/status"
healthcheckTimeout = 300

[services.rasa-server.env]
PORT = "5005"
RASA_MODEL_SERVER = "http://localhost:5005"

[[services]]
id = "web-dashboard"
name = "web-dashboard"
source = "web-dashboard"
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/"

[services.web-dashboard.env]
PORT = "80"
