language: "en"
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
  - name: EntitySynonymMapper
  - name: ResponseSelector
policies:
  - name: RulePolicy
  - name: MemoizationPolicy
  - name: TEDPolicy
